### ISSUE TITLE
FSDS Camera Intrinsic parameters are unknown

### ISSUE THREAD

**Issue by ChaitanyaLangde** [FS-Driverless/Formula-Student-Driverless-Simulator#345] opened 2022-10-16 17:57 UTC
Hello team,
Thank you for building such an amazing simulator. However, I wish to know the **intrinsic parameters** of the camera being used (specifically fx,fy,cx,cy) in the simulator, basically the camera matrix and if I can vary those as well for input arguments in the Perspective-n-Point algorithm to estimate the depth of the cones. I tried searching for it in the documentation but failed to do so.
Your support would be highly appreciated

**Comment by mateusz-lichota** [comment] 2022-10-18 16:40
I think this is a duplicate of #265, closing for now

**Closed by mateusz-lichota** 2022-10-18 16:40 UTC
Labels: duplicate
